default_language_version:
  python: python3.12

fail_fast: false

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
        - id: check-added-large-files
        - id: check-toml
        - id: check-yaml
        - id: end-of-file-fixer
        - id: trailing-whitespace
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.13.1
      hooks:
        - id: ruff
          args: [ --fix ]
        - id: ruff-format

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.18.1
      hooks:
        - id: mypy
          args: [--strict]
    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.10.0.1
      hooks:
        - id: shellcheck
